version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    platform: linux/arm64
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "6831:6831/udp"   # Jaeger thrift compact
      - "6832:6832/udp"   # Jaeger thrift binary
      - "5778:5778"       # Jaeger configs
      - "16686:16686"     # Jaeger UI
      - "4317:4317"       # OTLP gRPC
      - "4318:4318"       # OTLP HTTP
      - "14250:14250"     # Model/Proto
      - "14268:14268"     # Jaeger HTTP
      - "14269:14269"     # Admin
      - "9411:9411"       # Zipkin compatible endpoint
    networks:
      - monitoring

  otel-collector:
    image: otel/opentelemetry-collector:latest
    platform: linux/arm64
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./config/otel/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4316:4317"   # OTLP gRPC receiver
      - "4315:4318"   # OTLP http receiver
    depends_on:
      - jaeger
    networks:
      - monitoring

networks:
  monitoring:
    external: true
