version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: tiktok-toe-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/tiktok-toe
      - REDIS_URL=redis://redis:6379
      - MINIO_ENDPOINT=minio
      - ELASTICSEARCH_NODE=http://elasticsearch:9200
    depends_on:
      - mongodb
      - redis
      - minio
      - elasticsearch
    networks:
      - tiktok-toe-network

  mongodb:
    image: mongo:7
    container_name: tiktok-toe-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - tiktok-toe-network

  redis:
    image: redis:7-alpine
    container_name: tiktok-toe-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - tiktok-toe-network

  minio:
    image: minio/minio:latest
    container_name: tiktok-toe-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    networks:
      - tiktok-toe-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: tiktok-toe-elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    networks:
      - tiktok-toe-network

  mailhog:
    image: mailhog/mailhog:latest
    container_name: tiktok-toe-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - tiktok-toe-network

  prometheus:
    image: prom/prometheus:latest
    container_name: tiktok-toe-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - tiktok-toe-network

  grafana:
    image: grafana/grafana:latest
    container_name: tiktok-toe-grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
    networks:
      - tiktok-toe-network

volumes:
  mongodb_data:
  redis_data:
  minio_data:
  elasticsearch_data:
  prometheus_data:
  grafana_data:

networks:
  tiktok-toe-network:
    driver: bridge
