version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - BSKY_HANDLE=${BSKY_HANDLE}
      - BSKY_APP_PASSWORD=${BSKY_APP_PASSWORD}
      - BSKY_API_URL=${BSKY_API_URL}
      - BSKY_RATE_LIMIT=${BSKY_RATE_LIMIT}
      - BSKY_RATE_WINDOW=${BSKY_RATE_WINDOW}
    volumes:
      - ./data:/app/data
    networks:
      - app-network
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    platform: linux/arm64
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  redis_data:
