apiVersion: v1
kind: ConfigMap
metadata:
  name: tiktok-toe-config
  namespace: game-services
data:
  NODE_ENV: production
  LOG_LEVEL: info
  METRICS_ENABLED: "true"
  CACHE_TTL: "3600"
  MAX_CONNECTIONS: "1000"
  RATE_LIMIT: "100"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiktok-toe
  namespace: game-services
spec:
  replicas: 5
  template:
    spec:
      containers:
      - name: tiktok-toe
        resources:
          requests:
            cpu: "1000m"
            memory: "1Gi"
          limits:
            cpu: "2000m"
            memory: "2Gi"
        env:
        - name: ENABLE_CACHING
          value: "true"
        - name: ENABLE_RATE_LIMITING
          value: "true" 