global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - 'rules/*.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9094']

scrape_configs:
  - job_name: 'tiktok_toe_beta'
    metrics_path: '/metrics'
    basic_auth:
      username: prometheus
      password: Xy7+dQ9K2N5vM4pR8sT3wU6hJ1mB4nL9kF3qE5zW
    static_configs:
      - targets: ['localhost:3003']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'tiktok-toe-beta'
