global:
  resolve_timeout: 5m
  slack_api_url: '${SLACK_WEBHOOK_URL}'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'slack-notifications'
  routes:
    - match:
        severity: critical
      receiver: 'slack-critical'
      repeat_interval: 1h
      continue: true
    - match:
        severity: warning
      receiver: 'slack-warnings'
      repeat_interval: 2h
      continue: true
    - match_re:
        service: ^(api|worker|database|cache)$
      receiver: 'slack-services'
      group_by: ['alertname', 'service']
      continue: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#monitoring'
        send_resolved: true
        title: '[{{ .Status | toUpper }}] {{ .CommonLabels.alertname }}'
        text: >-
          {{ range .Alerts }}
            *Alert:* {{ .Annotations.summary }}
            *Description:* {{ .Annotations.description }}
            *Severity:* {{ .Labels.severity }}
            *Service:* {{ .Labels.service }}
            *Started:* {{ .StartsAt }}
          {{ end }}

  - name: 'slack-critical'
    slack_configs:
      - channel: '#incidents'
        send_resolved: true
        title: '[CRITICAL] {{ .CommonLabels.alertname }}'
        text: >-
          {{ range .Alerts }}
            *Alert:* {{ .Annotations.summary }}
            *Description:* {{ .Annotations.description }}
            *Service:* {{ .Labels.service }}
            *Started:* {{ .StartsAt }}
          {{ end }}

  - name: 'slack-warnings'
    slack_configs:
      - channel: '#warnings'
        send_resolved: true
        title: '[WARNING] {{ .CommonLabels.alertname }}'
        text: >-
          {{ range .Alerts }}
            *Alert:* {{ .Annotations.summary }}
            *Description:* {{ .Annotations.description }}
            *Service:* {{ .Labels.service }}
            *Started:* {{ .StartsAt }}
          {{ end }}

  - name: 'slack-services'
    slack_configs:
      - channel: '#services'
        send_resolved: true
        title: '[{{ .Status | toUpper }}] {{ .CommonLabels.service | toUpper }} - {{ .CommonLabels.alertname }}'
        text: >-
          {{ range .Alerts }}
            *Alert:* {{ .Annotations.summary }}
            *Description:* {{ .Annotations.description }}
            *Severity:* {{ .Labels.severity }}
            *Started:* {{ .StartsAt }}
          {{ end }}
