groups:
  - name: database_alerts
    rules:
      - alert: PostgresHighCPUUsage
        expr: rate(process_cpu_seconds_total{job="postgres"}[5m]) > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High CPU usage on PostgreSQL
          description: PostgreSQL instance has been using high CPU (> 80%) for the last 5 minutes.

      - alert: PostgresHighMemoryUsage
        expr: (process_resident_memory_bytes{job="postgres"} / container_memory_usage_bytes{container="postgres"}) * 100 > 90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High memory usage on PostgreSQL
          description: PostgreSQL instance is using more than 90% of allocated memory.

      - alert: PostgresLowCacheHitRatio
        expr: (pg_stat_database_blks_hit / (pg_stat_database_blks_hit + pg_stat_database_blks_read)) * 100 < 90
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: Low cache hit ratio
          description: PostgreSQL cache hit ratio is below 90% for the last 15 minutes.

      - alert: PostgresHighConnectionCount
        expr: pg_stat_activity_count > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High number of connections
          description: PostgreSQL has more than 80 active connections.

      - alert: PostgresLongRunningQueries
        expr: pg_stat_activity_max_tx_duration > 300
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Long running queries detected
          description: PostgreSQL has queries running longer than 5 minutes.

      - alert: RedisHighMemoryUsage
        expr: (redis_memory_used_bytes / redis_memory_max_bytes) * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High memory usage on Redis
          description: Redis instance is using more than 80% of allocated memory.

      - alert: RedisHighConnectionCount
        expr: redis_connected_clients > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High number of Redis connections
          description: Redis has more than 100 connected clients.

      - alert: RedisHighCommandLatency
        expr: rate(redis_commands_duration_seconds_sum[1m]) / rate(redis_commands_duration_seconds_count[1m]) > 0.01
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High Redis command latency
          description: Redis commands are taking longer than 10ms on average.

      - alert: RedisKeyEviction
        expr: rate(redis_evicted_keys_total[5m]) > 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Redis key eviction occurring
          description: Redis is evicting keys due to memory pressure.

      - alert: RedisRejectedConnections
        expr: rate(redis_rejected_connections_total[5m]) > 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Redis rejecting connections
          description: Redis is rejecting connections, possible max clients reached.
